### ISSUE TITLE
Problem with installation code.

### ISSUE THREAD

**Issue by weslleymberg** [tesonep/spaceAndTime#1]
Hi,

The code provided for installation didn't work for me. Maybe others will have the same problem.

I was able to load the package after changing the installation code to:

```
Metacello new
    baseline: 'SpaceAndTime';
    repository: 'github://tesonep/spaceAndTime/';
    load.
```

I changed the baseline name to use a capital 's' and used the 'load' message instead of 'yourself'.

**Comment by tesonep** [comment]
Thanks, I have fixed the documentation!
